<?php
/*
Template Name: Map
 */
get_header();
?>
<div class="layoutSingleColumn layoutSingleColumn--wide">
    <div class="u-marginTop30 header-map-note">
        <p>由于网络原因，地图加载可能需要一点时间。</p>
    </div>
    <div id="map" class="footer-map fa-mapper">
        <div class="lds-ripple">
        </div>
    </div>
    <div class="footer-map-note">
        <p>点击浮标可查看相关游记。</p>
        <p>灰色浮标代表已去过但没有相关游记。</p>
        <p>Map generated by <a href="https://fatesinger.com/100405" target="_blank" title="WordPress 插件Marker Pro" class="cute">Marker Pro</a>.</p>
    </div>
</div>
</div>
<div class="loadingBar"></div>
<?php get_footer('clean'); ?>